service: big-dota

package:
  include:
    - ~/.config/gcloud/application_default_credentials.json
    - ../big-dota-replay-parser-java/build/libs/dota-replay-parser-1.0-SNAPSHOT.jar
    - ../big-dota-replay-parser-java/resources/basic_replay.dem

provider:
  name: aws
  runtime: nodejs6.10

functions:
  queue-replay-ids:
    handler: big-dota-serverless-haskell.queue-replay-ids-exe

plugins:
  - serverless-haskell